# site settings
title: blog title
email: email@domain.com
description: "Description for landing page"
baseurl: "" # subpath, e.g. /blog
github_username: username
portfolio_website: http://portfolio.com

# build settings
markdown: kramdown

# matomo settings
# remove/comment lines to disable
matomo_trackerurl: "*.username.github.io"
matomo_sourceurl: "https://matomo.domain.com/"
matomo_siteid: 2

# isso settings
# remove/comment lines to disable
isso_dataurl: "https://isso.domain.com/"
isso_sourcecurl: "https://isso.domain.com/js/embed.min.js"
isso_vote: "false"
